### ISSUE TITLE
TypeError: Cannot create a consistent method resolution

### ISSUE THREAD

**Issue by cul11** [panhaoyu/amazon-sp-api-clients#8]
使用pip install amazon-sp-api-clients安装后，按Readme中所述编写 test.py文件，配置所需的6个参数，运行后报如下错误，不知是否版本兼容性问题：
[root@bingo pythons]# python3 testspapi.py
Traceback (most recent call last):
  File "testspapi.py", line 3, in <module>
    import amazon_sp_api_clients
  File "/usr/local/lib/python3.6/site-packages/amazon_sp_api_clients/__init__.py", line 1, in <module>
    from .aplus_content_2020_11_01 import AplusContent20201101Client
  File "/usr/local/lib/python3.6/site-packages/amazon_sp_api_clients/aplus_content_2020_11_01.py", line 871, in <module>
    class MessageSet(list, _List["Error"]):
  File "/usr/lib64/python3.6/typing.py", line 978, in __new__
    self = super().__new__(cls, name, bases, namespace, _root=True)
  File "/usr/lib64/python3.6/typing.py", line 137, in __new__
    return super().__new__(cls, name, bases, namespace)
  File "/usr/lib64/python3.6/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases list, List
[root@bingo pythons]#

当前python版本为：
[root@bingo pythons]# python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by panhaoyu** [comment]
Hello, could you please upgrade your python version? I develop the lib in python 3.9, and I think that at least python 3.7 is supported. But perhaps python 3.6 is not supported, because python 3.6 lacks of some type hints, and I may not support it. If possible, you can fork and create a branch, modify the `pyt` files, and remove all type hints. I feel sorry that I haven't solved your problem. If you need help when modifying the package, please feel free to contact me and I can provide you with some technical support.

你好，你能升级一下你的python版本吗?我用python 3.9开发这个库，我认为至少支持python 3.7。但可能不支持python 3.6，因为python 3.6缺少一些类型提示，我可能不支持它。如果可能的话，您可以派生并创建一个分支，修改`pyt`文件，并删除所有类型提示。我很抱歉没有解决你的问题。如果您在修改包的时候需要帮助，请随时联系我，我可以为您提供一些技术支持。

**Comment by cul11** [comment]
thanks alot!
